version: '3'

services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=surf-forecast
    ports:
      - 27017:27017
    volumes:
      - ./database/mongodb:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    ports:
      - 3000:3000
